### PR TITLE
fix bug when NOT filter around group(or|and|not)

### PR DESCRIPTION
**Pull request by Imbalanceone**
add group types in function  return_not_filter, because parse this string -   "(!(|(cn=admins)))"  returning None

### CODE REVIEW

**Comment by SteveEwell** [comment]
Thanks for the PR, give me a day or two to review the change and get the package updated. I haven't touched this project in a while

**Comment by Imbalanceone** [comment]
of course, let me know when you update the package

**Comment by Imbalanceone** [comment]
> Thanks for the PR, give me a day or two to review the change and get the package updated. I haven't touched this project in a while

Any difficulties with with my request?

**Comment by SteveEwell** [comment]
Lot happening at work and have been sidetracked. I can merge the PR but will probably not be able to publish the package update until this weekend.

**Pull request merged**
