### PR TITLE
extending regex filter

### PR DESCRIPTION
**Pull request by skelsec**
Extending regex filter to allow filters like
```userAccountControl:1.2.840.113556.1.4.803:=4194304```

### CODE REVIEW

**Comment by peppelinux** [comment]
This should be merged

**Comment by SteveEwell** [comment]
I'll try and get the pip module updated this weekend.

**Comment by peppelinux** [comment]
Gorgeous lib this!
I found It today, I'll start to use It for extending pymultildap for RDBMS integration. It Will take LDAP searches, parse them (thank of this) and create sqlalchemy search filters.

This permit my Middleware to stay behind openldap and fetch data from multiple data sources...

Awesome lib

**Comment by SteveEwell** [comment]
@skelsec Your fix has been pushed to PyPi in version `0.2.2`, thanks for the contrib!

@peppelinux Thanks! Glad you find it useful. I worked in InfoSec for a while and I originally wrote it for generating LDAP filters for user provisioning rules. Figured it might be useful for others as well.

**Pull request merged**
